
FROM nvidia/cuda:9.1-cudnn7-devel-ubuntu16.04

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
    wget \
    bzip2 \
    ca-certificates \
    sudo \
    locales \
    fonts-liberation \
    python3-dev \ 
    python3-pip \
    python3-wheel \
    python3-setuptools \
    git \
    wget \
    autoconf \
    libtool \
    automake \
    libx11-6 &&\
    rm -rf /var/lib/apt/lists/*	/var/cache/apt/archives/*

RUN pip3 install --no-cache-dir cupy-cuda91==5.0.0b3 chainer==5.0.0b3 chainer-chemistry

RUN pip3 install numpy scipy pandas sklearn joblib bokeh
RUN pip3 install --upgrade pip
RUN pip3 install jupyter
RUN pip3 install tifffile
RUN pip3 install matplotlib
RUN pip3 install glob3
RUN pip3 install opencv-python

ENV TZ Asia/Tokyo
RUN apt-get update \
  && apt-get -y --no-install-recommends install libglib2.0-0
RUN apt-get -y --no-install-recommends install libsm6 libxext6
RUN apt-get -y --no-install-recommends install libxrender-dev
RUN apt-get -y --no-install-recommends install flex



RUN mkdir /host_mount
WORKDIR host_mount

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
  && apt-get install -y tzdata \
  && rm -rf /var/lib/apt/lists/* \
  && echo "${TZ}" > /etc/timezone \
  && rm /etc/localtime \
  && ln -s /usr/share/zoneinfo/Asia/Tokyo /etc/localtime \
  && dpkg-reconfigure -f noninteractive tzdata
RUN apt-get update
RUN apt-get -y install python3-tk
RUN apt-get -y install nano
RUN apt-get -y install ssh
RUN pip3 install  enum34
RUN pip3 install chainerui
RUN sed -i s/TkAgg/Agg/g  /usr/local/lib/python3.5/dist-packages/matplotlib/mpl-data/matplotlibrc
#CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--no-browser", "--allow-root"]
